{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 85,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Extracting mnist/train-images-idx3-ubyte.gz\n",
      "Extracting mnist/train-labels-idx1-ubyte.gz\n",
      "Extracting mnist/t10k-images-idx3-ubyte.gz\n",
      "Extracting mnist/t10k-labels-idx1-ubyte.gz\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "from tensorflow.examples.tutorials.mnist import input_data\n",
    "mnist = input_data.read_data_sets('mnist/',one_hot=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train = mnist.train.images\n",
    "Y_train = mnist.train.labels\n",
    "X_test = mnist.test.images\n",
    "Y_test = mnist.test.labels"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "metadata": {},
   "outputs": [],
   "source": [
    "Y_train=np.asarray(Y_train,dtype=np.int32)\n",
    "Y_test=np.asarray(Y_test,dtype=np.int32)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(55000, 784)"
      ]
     },
     "execution_count": 88,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_train.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(10000, 784)"
      ]
     },
     "execution_count": 89,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_test.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "7"
      ]
     },
     "execution_count": 90,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "Y_train[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Text(0.5, 1.0, 'O numero é 7')"
      ]
     },
     "execution_count": 91,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAPsAAAEICAYAAACZA4KlAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAQ+UlEQVR4nO3dfbBU9X3H8fcniMGHVDQqEiTcgI+lnaIijTHtWB8S5R9NqxhmVHxIrjqaUQdbrXEaO2Nn0gwEndrqYKViGrGx8QFtHgTGDLHUB3AoF4OJDwFBkAcf4BKsRvz2jz04K95z9rJPZ+/9fV4zO3f3fM85+70793PPOXt2z08RgZkNfp8quwEzaw+H3SwRDrtZIhx2s0Q47GaJcNjNEuGwW+kkTZG0QNKwsnsZzBz2kkm6WFKPpB2S3pB0p6ThZffVLpKOAy4DzomI/8uZ588kbd/tFpL+qr3dDmzyh2rKI2k68DfANGARMAr4F+AQ4OSIeL/E9vaIpL0i4oM2PdcpwGPAYRHxu3Y852DgLXtJJP0B8PfAtyLiZxHx+4hYDUwBxgAX5Cx3r6R/lvRfknolPSNpXFbryrZ4e1XN/wtJ38juXyzpvyXNkvSOpFclfSmbvlbSJknTqpb9tKQZkl6TtFHSXZL2yWqnSFon6QZJbwD/ls1/m6T12e02SZ8ueA0ulbRK0tuSfi5pTD9fvmnAfzroe8ZhL8+XgGHAQ9UTI2I78FPgjIJlp1L5R3Eg8DLwD3vwvH8KrAA+C9wPPACcCBxB5R/MHZL2z+b9R+AoYEJWHwX8XdW6DgMOovLPqRv4NvDFbP4/ASYBN/fVhKRzgJuAv6SyJ/NLYF6t5iXtC5wLzO3n72u7RIRvJdyoBOuNnNp3gQU5tXuBf616PBl4MbvfBQSwV1X9F8A3svsXAy9V1f44m39E1bQ3qYRVwO+AcVW1k4DfZvdPAd4HhlXVXwEmVz3+KrA65/f4KXBZ1eNPATuAMTVetwuB35IdgvrW/9tHu3vWdluAg3OOdUdm9TxvVN3fAeyfN2MfNlbdfxcgInaftj+Vre2+wDJJu2oChlTNuzk+/qba54A1VY/XZNP6Mga4XdLMqmmisvewpu9FgMou/H2RJd/6z7vx5fkf4D0qu7EfkbQfcBaVN+z21K5j2H2rph1WV3eVfzbvAuMjYnh2OyAiqv+x7B649VRCvMvns2l9WQtcXrXu4RGxT0QsyWtI0mgqexT37ekvYw57aSJiK5Xj7n+SdKakoZK6gAeBdcAP6ljnZuB14AJJQyRdCoyrs78PgbuBWZIOBZA0StJXCxabB9ws6RBJB1M5vv/3nHnvAv5W0vhs3QdIOq9GWxcCSyLilT35XazCYS9RRHyPyptUM4BtwDNUtninRcR7da72m8BfUzn2Hg/kbin74QYqbwA+LWkbsBA4umD+W4GlVN4A7AGez6Z9QkQ8TOUNwAeyda+kskdT5CL8xlzdfJ7dLBHespslwmE3S4TDbpYIh90sEW39UI0kvxto1mIRob6mN7Rlz84P/1rSy5JubGRdZtZadZ96kzQE+A2VL2ysA54DpkbErwqW8ZbdrMVasWWfBLwcEa9G5XvXDwBnN7A+M2uhRsI+isqnvXZZl037GEndkpZKWtrAc5lZgxp5g66vXYVP7KZHxGxgNng33qxMjWzZ1wGjqx4fTv43nMysZI2E/TngSElfkLQ38HVgfnPaMrNmq3s3PiI+kHQ18HMqFzSYExEvNK0zM2uqtn7rzcfsZq3Xkg/VmNnA4bCbJcJhN0uEw26WCIfdLBEOu1kiHHazRDjsZolw2M0S4bCbJcJhN0uEw26WCIfdLBEOu1kiHHazRDjsZolw2M0S4bCbJcJhN0uEw26WCIfdLBEOu1kiHHazRDjsZolw2M0S4bCbJcJhN0uEw26WCIfdLBEOu1ki6h6fHUDSaqAX2Al8EBETm9GUmTVfQ2HP/EVEbGnCesyshbwbb5aIRsMewBOSlknq7msGSd2Slkpa2uBzmVkDFBH1Lyx9LiLWSzoUWAB8KyIWF8xf/5OZWb9EhPqa3tCWPSLWZz83AQ8DkxpZn5m1Tt1hl7SfpM/sug98BVjZrMbMrLkaeTd+BPCwpF3ruT8iftaUrsys6Ro6Zt/jJ/Mxu1nLteSY3cwGDofdLBEOu1kiHHazRDjsZoloxhdhrGSXXHJJbq3W2ZY333yzsH7ssccW1pcsWVJYf+qppwrr1j7espslwmE3S4TDbpYIh90sEQ67WSIcdrNEOOxmiRg059mnTp1aWD/++OML60Xnqjvd8OHD6152586dhfW99967sP7uu+8W1nfs2JFb6+npKVx2ypQphfXNmzcX1u3jvGU3S4TDbpYIh90sEQ67WSIcdrNEOOxmiXDYzRIxoK4uO3PmzNzaNddcU7jskCFDGnlqK8GTTz5ZWK/12YqNGzc2s50Bw1eXNUucw26WCIfdLBEOu1kiHHazRDjsZolw2M0SMaDOs69duza3dvjhhxcuu2LFisJ6re9lt1Kta6s/8sgjbepkz51xxhmF9Ysuuii31tXV1dBz1zoPf/755+fWBvN34es+zy5pjqRNklZWTTtI0gJJL2U/D2xms2bWfP3Zjb8XOHO3aTcCiyLiSGBR9tjMOljNsEfEYuCt3SafDczN7s8FzmlyX2bWZPVeg25ERGwAiIgNkg7Nm1FSN9Bd5/OYWZO0/IKTETEbmA2Nv0FnZvWr99TbRkkjAbKfm5rXkpm1Qr1hnw9My+5PAx5tTjtm1io1z7NLmgecAhwMbAS+AzwC/Aj4PPAacF5E7P4mXl/ramg3/qijjsqtjR8/vnDZhQsXFtZ7e3vr6smKjR07Nrf2+OOPFy5ba2z4Wq6//vrcWtG1EQa6vPPsNY/ZIyLvCgGnNdSRmbWVPy5rlgiH3SwRDrtZIhx2s0Q47GaJGFBfcbXB5dxzzy2sP/jggw2tf8uWLbm1Qw45pKF1dzJfStoscQ67WSIcdrNEOOxmiXDYzRLhsJslwmE3S4TDbpYIh90sEQ67WSIcdrNEOOxmiXDYzRLhsJslwmE3S0TLR4SxtF155ZW5tRNPPLGlzz1s2LDc2gknnFC47LJly5rdTum8ZTdLhMNulgiH3SwRDrtZIhx2s0Q47GaJcNjNEuHrxg8CI0eOzK1dcMEFhctee+21zW7nY4p6k/q8vHlbbNu2rbB+wAEHtKmT5qv7uvGS5kjaJGll1bRbJL0uaXl2m9zMZs2s+fqzG38vcGYf02dFxITs9pPmtmVmzVYz7BGxGHirDb2YWQs18gbd1ZJWZLv5B+bNJKlb0lJJSxt4LjNrUL1hvxMYB0wANgAz82aMiNkRMTEiJtb5XGbWBHWFPSI2RsTOiPgQuBuY1Ny2zKzZ6gq7pOrzKV8DVubNa2adoeb32SXNA04BDpa0DvgOcIqkCUAAq4HLW9jjoHf66acX1mt997q7uzu3Nnbs2Lp6GuzmzJlTdgttVzPsETG1j8n3tKAXM2shf1zWLBEOu1kiHHazRDjsZolw2M0S4UtJN8ERRxxRWL/rrrsK66eeemphvZVfBV2zZk1h/e23325o/TfffHNu7b333itc9o477iisH3300XX1BLB+/fq6lx2ovGU3S4TDbpYIh90sEQ67WSIcdrNEOOxmiXDYzRLh8+z9dN111+XWrrrqqsJlx40bV1jfvn17Yf2dd94prN922225tVrnk5csWVJYr3UevpW2bt3a0PK9vb25tccee6yhdQ9E3rKbJcJhN0uEw26WCIfdLBEOu1kiHHazRDjsZonwefZ+Oumkk3Jrtc6jz58/v7A+c2bugDoALF68uLA+UE2YMKGwPmbMmIbWX/R9+RdffLGhdQ9E3rKbJcJhN0uEw26WCIfdLBEOu1kiHHazRDjsZonoz5DNo4H7gMOAD4HZEXG7pIOA/wC6qAzbPCUiGrvIeAe74oorcmsrVqwoXPbWW29tdjuDQq3r7Y8YMaKh9S9cuLCh5Qeb/mzZPwCmR8SxwBeBqyT9IXAjsCgijgQWZY/NrEPVDHtEbIiI57P7vcAqYBRwNjA3m20ucE6rmjSzxu3RMbukLuA44BlgRERsgMo/BODQZjdnZs3T78/GS9of+DFwbURs6+/4Y5K6ge762jOzZunXll3SUCpB/2FEPJRN3ihpZFYfCWzqa9mImB0REyNiYjMaNrP61Ay7Kpvwe4BVEfH9qtJ8YFp2fxrwaPPbM7NmUUQUzyB9Gfgl0EPl1BvATVSO238EfB54DTgvIt6qsa7iJ7OkzJgxo7A+ffr0wnqtS2yfddZZubWnn366cNmBLCL6PMauecweEU8BeQfopzXSlJm1jz9BZ5YIh90sEQ67WSIcdrNEOOxmiXDYzRLhS0lbS/X09OTWjjnmmIbW/cQTTxTWB/O59Hp4y26WCIfdLBEOu1kiHHazRDjsZolw2M0S4bCbJcLn2a2lurq6cmt77VX857d169bC+qxZs+ppKVnespslwmE3S4TDbpYIh90sEQ67WSIcdrNEOOxmifB5dmvI1KlTC+v77LNPbq23t7dw2e7u4lHD/H31PeMtu1kiHHazRDjsZolw2M0S4bCbJcJhN0uEw26WiP6Mzz4auA84jMr47LMj4nZJtwDfBDZns94UET+psS6Pzz7ADB06tLD+7LPPFtaLrg0/b968wmUvvfTSwrr1re7x2YEPgOkR8bykzwDLJC3IarMiYkazmjSz1qkZ9ojYAGzI7vdKWgWManVjZtZce3TMLqkLOA54Jpt0taQVkuZIOjBnmW5JSyUtbahTM2tIv8MuaX/gx8C1EbENuBMYB0ygsuWf2ddyETE7IiZGxMQm9GtmdepX2CUNpRL0H0bEQwARsTEidkbEh8DdwKTWtWlmjaoZdkkC7gFWRcT3q6aPrJrta8DK5rdnZs3Sn3fjTwYuBHokLc+m3QRMlTQBCGA1cHlLOrRS1To1e//99xfWly9fnltbsGBBbs2arz/vxj8F9HXervCcupl1Fn+CziwRDrtZIhx2s0Q47GaJcNjNEuGwmyWi5ldcm/pk/oqrWcvlfcXVW3azRDjsZolw2M0S4bCbJcJhN0uEw26WCIfdLBHtHrJ5C7Cm6vHB2bRO1Km9dWpf4N7q1czexuQV2vqhmk88ubS0U69N16m9dWpf4N7q1a7evBtvlgiH3SwRZYd9dsnPX6RTe+vUvsC91astvZV6zG5m7VP2lt3M2sRhN0tEKWGXdKakX0t6WdKNZfSQR9JqST2Slpc9Pl02ht4mSSurph0kaYGkl7KffY6xV1Jvt0h6PXvtlkuaXFJvoyU9KWmVpBckXZNNL/W1K+irLa9b24/ZJQ0BfgOcAawDngOmRsSv2tpIDkmrgYkRUfoHMCT9ObAduC8i/iib9j3grYj4bvaP8sCIuKFDersF2F72MN7ZaEUjq4cZB84BLqbE166grym04XUrY8s+CXg5Il6NiPeBB4CzS+ij40XEYuCt3SafDczN7s+l8sfSdjm9dYSI2BARz2f3e4Fdw4yX+toV9NUWZYR9FLC26vE6Omu89wCekLRMUnfZzfRhRERsgMofD3Boyf3sruYw3u202zDjHfPa1TP8eaPKCHtf18fqpPN/J0fE8cBZwFXZ7qr1T7+G8W6XPoYZ7wj1Dn/eqDLCvg4YXfX4cGB9CX30KSLWZz83AQ/TeUNRb9w1gm72c1PJ/Xykk4bx7muYcTrgtStz+PMywv4ccKSkL0jaG/g6ML+EPj5B0n7ZGydI2g/4Cp03FPV8YFp2fxrwaIm9fEynDOOdN8w4Jb92pQ9/HhFtvwGTqbwj/wrw7TJ6yOlrLPC/2e2FsnsD5lHZrfs9lT2iy4DPAouAl7KfB3VQbz8AeoAVVII1sqTevkzl0HAFsDy7TS77tSvoqy2vmz8ua5YIf4LOLBEOu1kiHHazRDjsZolw2M0S4bCbJcJhN0vE/wO+aLAjJW8ydgAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "plt.imshow(X_train[0].reshape((28,28)),cmap='gray')\n",
    "plt.title('O numero é '+str(Y_train[0]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 96,
   "metadata": {},
   "outputs": [],
   "source": [
    "def cria_rede(features, labels, mode):\n",
    "    #batch_size, largura, altura, canais(RGB)\n",
    "    entrada = tf.reshape(features['X'],[-1,28,28,1])#-1 == None tf.placeholders\n",
    "    \n",
    "    #recebe {batch_size,28,28,1} 1 canal por ser cinza\n",
    "    #retorna {batch_size,28,28,32} 32 mapas de caracteristicas \n",
    "    convolucao1 = tf.layers.conv2d(inputs=entrada, filters=32, kernel_size=[5,5],\n",
    "                                  activation=tf.nn.relu, padding='same') #32 mapas de caracteristicas\n",
    "    \n",
    "    #simplifica quadrados de 2x2 pulando de 2 em 2\n",
    "    #recebe {batch_size,28,28,32}\n",
    "    #retorna {batch_size,14,14,32} com 32 'versoes' da imagem\n",
    "    pooling1=tf.layers.max_pooling2d(inputs=convolucao1,pool_size=[2,2],strides=2) \n",
    "    \n",
    "    #recebe {batch_size,14,14,32} \n",
    "    #retorna {batch_size,14,14,64} \n",
    "    convolucao2 = tf.layers.conv2d(inputs = pooling1, filters=64, kernel_size=[5,5],\n",
    "                                    activation = tf.nn.relu, padding='same')\n",
    "    #recebe {batch_size,14,14,64} \n",
    "    #retorna {batch_size,7,7,64} \n",
    "    pooling2=tf.layers.max_pooling2d(inputs=convolucao2,pool_size=[2,2],strides=2)\n",
    "    \n",
    "    #recebe {batch_size,-1,-1,64} \n",
    "    #retorna {batch_size,3136} \n",
    "    flattening = tf.reshape(pooling2, [-1,7*7*64])#transformar em array pra entrada em uma rede neural\n",
    "    \n",
    "    #3184 -> 1024 -> 10(saida)\n",
    "    #recebe {batch_size,3136} \n",
    "    #retorna {batch_size,1024} \n",
    "    densa=tf.layers.dense(inputs=flattening,units=1024, activation=tf.nn.relu)\n",
    "    \n",
    "    #dropout\n",
    "    dropout = tf.layers.dropout(inputs=densa,rate=0.2, training = mode == tf.estimator.ModeKeys.TRAIN)\n",
    "    \n",
    "    #recebe {batch_size,1024} \n",
    "    #retorna {batch_size,10} \n",
    "    saida=tf.layers.dense(inputs=dropout, units=10)\n",
    "    \n",
    "    #0.2 0.2 0.6\n",
    "    \n",
    "    previsoes = tf.argmax(saida, axis=1)\n",
    "    \n",
    "    if mode == tf.estimator.ModeKeys.PREDICT:\n",
    "        return tf.estimator.EstimatorSpec(mode=mode, predictions=previsoes )\n",
    "    \n",
    "    erro = tf.losses.sparse_softmax_cross_entropy(labels=labels,logits=saida)\n",
    "    \n",
    "    if mode == tf.estimator.ModeKeys.TRAIN:\n",
    "        otimizador = tf.train.AdamOptimizer(learning_rate=0.001)\n",
    "        treinamento = otimizador.minimize(erro, global_step = tf.train.get_global_step())\n",
    "        return tf.estimator.EstimatorSpec(mode = mode, loss=erro, train_op=treinamento)\n",
    "    if mode == tf.estimator.ModeKeys.EVAL:\n",
    "        eval_metrics_ops={'accuracy':tf.metrics.accuracy(labels=labels, predictions=previsoes)}\n",
    "        return tf.estimator.EstimatorSpec(mode = mode, loss=erro, eval_metric_ops=eval_metrics_ops)        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 97,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Using default config.\n",
      "WARNING:tensorflow:Using temporary folder as model directory: C:\\Users\\lukas\\AppData\\Local\\Temp\\tmpycro1in0\n",
      "INFO:tensorflow:Using config: {'_model_dir': 'C:\\\\Users\\\\lukas\\\\AppData\\\\Local\\\\Temp\\\\tmpycro1in0', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true\n",
      "graph_options {\n",
      "  rewrite_options {\n",
      "    meta_optimizer_iterations: ONE\n",
      "  }\n",
      "}\n",
      ", '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000020B22288648>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n"
     ]
    }
   ],
   "source": [
    "classificador = tf.estimator.Estimator(cria_rede)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 98,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Calling model_fn.\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B20B2BA48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B20B2BA48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B20B2BA48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B20B2BA48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B1E9A7988>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B1E9A7988>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B1E9A7988>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B1E9A7988>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B1D242308>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B1D242308>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B1D242308>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B1D242308>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B26DEE648>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B26DEE648>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B26DEE648>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B26DEE648>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B1E9A7988>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B1E9A7988>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B1E9A7988>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B1E9A7988>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x0000020B1E9A7988>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x0000020B1E9A7988>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x0000020B1E9A7988>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x0000020B1E9A7988>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B1E9A7988>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B1E9A7988>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B1E9A7988>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B1E9A7988>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into C:\\Users\\lukas\\AppData\\Local\\Temp\\tmpycro1in0\\model.ckpt.\n",
      "INFO:tensorflow:loss = 2.3017983, step = 1\n",
      "INFO:tensorflow:global_step/sec: 4.52755\n",
      "INFO:tensorflow:loss = 0.0880193, step = 101 (22.089 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 200 into C:\\Users\\lukas\\AppData\\Local\\Temp\\tmpycro1in0\\model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.12127311.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<tensorflow_estimator.python.estimator.estimator.Estimator at 0x20b22288208>"
      ]
     },
     "execution_count": 98,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "func_train = tf.estimator.inputs.numpy_input_fn(x={'X':X_train},y=Y_train,batch_size=128,\n",
    "                                               num_epochs=None, shuffle=True)\n",
    "classificador.train(input_fn=func_train,steps=200)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 99,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Calling model_fn.\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B202CA148>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B202CA148>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B202CA148>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B202CA148>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B2293D648>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B2293D648>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B2293D648>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B2293D648>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B256E93C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B256E93C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B256E93C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B256E93C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B2015E408>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B2015E408>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B2015E408>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B2015E408>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B22E9A708>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B22E9A708>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B22E9A708>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B22E9A708>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x0000020B22E766C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x0000020B22E766C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x0000020B22E766C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x0000020B22E766C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B22E766C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B22E766C8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B22E766C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B22E766C8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-10-01T15:20:01Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\lukas\\AppData\\Local\\Temp\\tmpycro1in0\\model.ckpt-200\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Finished evaluation at 2020-10-01-15:20:07\n",
      "INFO:tensorflow:Saving dict for global step 200: accuracy = 0.9729, global_step = 200, loss = 0.08538556\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 200: C:\\Users\\lukas\\AppData\\Local\\Temp\\tmpycro1in0\\model.ckpt-200\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'accuracy': 0.9729, 'loss': 0.08538556, 'global_step': 200}"
      ]
     },
     "execution_count": 99,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "func_test= tf.estimator.inputs.numpy_input_fn(x={'X':X_test},y=Y_test, num_epochs=1, shuffle=False)\n",
    "resultados = classificador.evaluate(input_fn=func_test)\n",
    "resultados"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 100,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(784,)"
      ]
     },
     "execution_count": 100,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_image_teste = X_test[0]\n",
    "X_image_teste.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 101,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(1, 784)"
      ]
     },
     "execution_count": 101,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_image_teste = X_image_teste.reshape(1,-1)\n",
    "X_image_teste.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 102,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Calling model_fn.\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B25816A88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B25816A88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B25816A88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B25816A88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B20FF0B88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B20FF0B88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B20FF0B88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B20FF0B88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B256D5B88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B256D5B88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B256D5B88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000020B256D5B88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B20A72BC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B20A72BC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B20A72BC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x0000020B20A72BC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B22DE61C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B22DE61C8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B22DE61C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B22DE61C8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x0000020B1E9C1BC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x0000020B1E9C1BC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x0000020B1E9C1BC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x0000020B1E9C1BC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B1E9C1BC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B1E9C1BC8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B1E9C1BC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000020B1E9C1BC8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\lukas\\AppData\\Local\\Temp\\tmpycro1in0\\model.ckpt-200\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n"
     ]
    }
   ],
   "source": [
    "func_previsao = tf.estimator.inputs.numpy_input_fn(x={'X':X_image_teste},shuffle=False)\n",
    "pred = list(classificador.predict(input_fn=func_previsao))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Text(0.5, 1.0, 'O numero é 7')"
      ]
     },
     "execution_count": 103,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAPsAAAEICAYAAACZA4KlAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAQ+UlEQVR4nO3dfbBU9X3H8fcniMGHVDQqEiTcgI+lnaIijTHtWB8S5R9NqxhmVHxIrjqaUQdbrXEaO2Nn0gwEndrqYKViGrGx8QFtHgTGDLHUB3AoF4OJDwFBkAcf4BKsRvz2jz04K95z9rJPZ+/9fV4zO3f3fM85+70793PPOXt2z08RgZkNfp8quwEzaw+H3SwRDrtZIhx2s0Q47GaJcNjNEuGwW+kkTZG0QNKwsnsZzBz2kkm6WFKPpB2S3pB0p6ThZffVLpKOAy4DzomI/8uZ588kbd/tFpL+qr3dDmzyh2rKI2k68DfANGARMAr4F+AQ4OSIeL/E9vaIpL0i4oM2PdcpwGPAYRHxu3Y852DgLXtJJP0B8PfAtyLiZxHx+4hYDUwBxgAX5Cx3r6R/lvRfknolPSNpXFbryrZ4e1XN/wtJ38juXyzpvyXNkvSOpFclfSmbvlbSJknTqpb9tKQZkl6TtFHSXZL2yWqnSFon6QZJbwD/ls1/m6T12e02SZ8ueA0ulbRK0tuSfi5pTD9fvmnAfzroe8ZhL8+XgGHAQ9UTI2I78FPgjIJlp1L5R3Eg8DLwD3vwvH8KrAA+C9wPPACcCBxB5R/MHZL2z+b9R+AoYEJWHwX8XdW6DgMOovLPqRv4NvDFbP4/ASYBN/fVhKRzgJuAv6SyJ/NLYF6t5iXtC5wLzO3n72u7RIRvJdyoBOuNnNp3gQU5tXuBf616PBl4MbvfBQSwV1X9F8A3svsXAy9V1f44m39E1bQ3qYRVwO+AcVW1k4DfZvdPAd4HhlXVXwEmVz3+KrA65/f4KXBZ1eNPATuAMTVetwuB35IdgvrW/9tHu3vWdluAg3OOdUdm9TxvVN3fAeyfN2MfNlbdfxcgInaftj+Vre2+wDJJu2oChlTNuzk+/qba54A1VY/XZNP6Mga4XdLMqmmisvewpu9FgMou/H2RJd/6z7vx5fkf4D0qu7EfkbQfcBaVN+z21K5j2H2rph1WV3eVfzbvAuMjYnh2OyAiqv+x7B649VRCvMvns2l9WQtcXrXu4RGxT0QsyWtI0mgqexT37ekvYw57aSJiK5Xj7n+SdKakoZK6gAeBdcAP6ljnZuB14AJJQyRdCoyrs78PgbuBWZIOBZA0StJXCxabB9ws6RBJB1M5vv/3nHnvAv5W0vhs3QdIOq9GWxcCSyLilT35XazCYS9RRHyPyptUM4BtwDNUtninRcR7da72m8BfUzn2Hg/kbin74QYqbwA+LWkbsBA4umD+W4GlVN4A7AGez6Z9QkQ8TOUNwAeyda+kskdT5CL8xlzdfJ7dLBHespslwmE3S4TDbpYIh90sEW39UI0kvxto1mIRob6mN7Rlz84P/1rSy5JubGRdZtZadZ96kzQE+A2VL2ysA54DpkbErwqW8ZbdrMVasWWfBLwcEa9G5XvXDwBnN7A+M2uhRsI+isqnvXZZl037GEndkpZKWtrAc5lZgxp5g66vXYVP7KZHxGxgNng33qxMjWzZ1wGjqx4fTv43nMysZI2E/TngSElfkLQ38HVgfnPaMrNmq3s3PiI+kHQ18HMqFzSYExEvNK0zM2uqtn7rzcfsZq3Xkg/VmNnA4bCbJcJhN0uEw26WCIfdLBEOu1kiHHazRDjsZolw2M0S4bCbJcJhN0uEw26WCIfdLBEOu1kiHHazRDjsZolw2M0S4bCbJcJhN0uEw26WCIfdLBEOu1kiHHazRDjsZolw2M0S4bCbJcJhN0uEw26WCIfdLBEOu1ki6h6fHUDSaqAX2Al8EBETm9GUmTVfQ2HP/EVEbGnCesyshbwbb5aIRsMewBOSlknq7msGSd2Slkpa2uBzmVkDFBH1Lyx9LiLWSzoUWAB8KyIWF8xf/5OZWb9EhPqa3tCWPSLWZz83AQ8DkxpZn5m1Tt1hl7SfpM/sug98BVjZrMbMrLkaeTd+BPCwpF3ruT8iftaUrsys6Ro6Zt/jJ/Mxu1nLteSY3cwGDofdLBEOu1kiHHazRDjsZoloxhdhrGSXXHJJbq3W2ZY333yzsH7ssccW1pcsWVJYf+qppwrr1j7espslwmE3S4TDbpYIh90sEQ67WSIcdrNEOOxmiRg059mnTp1aWD/++OML60Xnqjvd8OHD6152586dhfW99967sP7uu+8W1nfs2JFb6+npKVx2ypQphfXNmzcX1u3jvGU3S4TDbpYIh90sEQ67WSIcdrNEOOxmiXDYzRIxoK4uO3PmzNzaNddcU7jskCFDGnlqK8GTTz5ZWK/12YqNGzc2s50Bw1eXNUucw26WCIfdLBEOu1kiHHazRDjsZolw2M0SMaDOs69duza3dvjhhxcuu2LFisJ6re9lt1Kta6s/8sgjbepkz51xxhmF9Ysuuii31tXV1dBz1zoPf/755+fWBvN34es+zy5pjqRNklZWTTtI0gJJL2U/D2xms2bWfP3Zjb8XOHO3aTcCiyLiSGBR9tjMOljNsEfEYuCt3SafDczN7s8FzmlyX2bWZPVeg25ERGwAiIgNkg7Nm1FSN9Bd5/OYWZO0/IKTETEbmA2Nv0FnZvWr99TbRkkjAbKfm5rXkpm1Qr1hnw9My+5PAx5tTjtm1io1z7NLmgecAhwMbAS+AzwC/Aj4PPAacF5E7P4mXl/ramg3/qijjsqtjR8/vnDZhQsXFtZ7e3vr6smKjR07Nrf2+OOPFy5ba2z4Wq6//vrcWtG1EQa6vPPsNY/ZIyLvCgGnNdSRmbWVPy5rlgiH3SwRDrtZIhx2s0Q47GaJGFBfcbXB5dxzzy2sP/jggw2tf8uWLbm1Qw45pKF1dzJfStoscQ67WSIcdrNEOOxmiXDYzRLhsJslwmE3S4TDbpYIh90sEQ67WSIcdrNEOOxmiXDYzRLhsJslwmE3S0TLR4SxtF155ZW5tRNPPLGlzz1s2LDc2gknnFC47LJly5rdTum8ZTdLhMNulgiH3SwRDrtZIhx2s0Q47GaJcNjNEuHrxg8CI0eOzK1dcMEFhctee+21zW7nY4p6k/q8vHlbbNu2rbB+wAEHtKmT5qv7uvGS5kjaJGll1bRbJL0uaXl2m9zMZs2s+fqzG38vcGYf02dFxITs9pPmtmVmzVYz7BGxGHirDb2YWQs18gbd1ZJWZLv5B+bNJKlb0lJJSxt4LjNrUL1hvxMYB0wANgAz82aMiNkRMTEiJtb5XGbWBHWFPSI2RsTOiPgQuBuY1Ny2zKzZ6gq7pOrzKV8DVubNa2adoeb32SXNA04BDpa0DvgOcIqkCUAAq4HLW9jjoHf66acX1mt997q7uzu3Nnbs2Lp6GuzmzJlTdgttVzPsETG1j8n3tKAXM2shf1zWLBEOu1kiHHazRDjsZolw2M0S4UtJN8ERRxxRWL/rrrsK66eeemphvZVfBV2zZk1h/e23325o/TfffHNu7b333itc9o477iisH3300XX1BLB+/fq6lx2ovGU3S4TDbpYIh90sEQ67WSIcdrNEOOxmiXDYzRLh8+z9dN111+XWrrrqqsJlx40bV1jfvn17Yf2dd94prN922225tVrnk5csWVJYr3UevpW2bt3a0PK9vb25tccee6yhdQ9E3rKbJcJhN0uEw26WCIfdLBEOu1kiHHazRDjsZonwefZ+Oumkk3Jrtc6jz58/v7A+c2bugDoALF68uLA+UE2YMKGwPmbMmIbWX/R9+RdffLGhdQ9E3rKbJcJhN0uEw26WCIfdLBEOu1kiHHazRDjsZonoz5DNo4H7gMOAD4HZEXG7pIOA/wC6qAzbPCUiGrvIeAe74oorcmsrVqwoXPbWW29tdjuDQq3r7Y8YMaKh9S9cuLCh5Qeb/mzZPwCmR8SxwBeBqyT9IXAjsCgijgQWZY/NrEPVDHtEbIiI57P7vcAqYBRwNjA3m20ucE6rmjSzxu3RMbukLuA44BlgRERsgMo/BODQZjdnZs3T78/GS9of+DFwbURs6+/4Y5K6ge762jOzZunXll3SUCpB/2FEPJRN3ihpZFYfCWzqa9mImB0REyNiYjMaNrP61Ay7Kpvwe4BVEfH9qtJ8YFp2fxrwaPPbM7NmUUQUzyB9Gfgl0EPl1BvATVSO238EfB54DTgvIt6qsa7iJ7OkzJgxo7A+ffr0wnqtS2yfddZZubWnn366cNmBLCL6PMauecweEU8BeQfopzXSlJm1jz9BZ5YIh90sEQ67WSIcdrNEOOxmiXDYzRLhS0lbS/X09OTWjjnmmIbW/cQTTxTWB/O59Hp4y26WCIfdLBEOu1kiHHazRDjsZolw2M0S4bCbJcLn2a2lurq6cmt77VX857d169bC+qxZs+ppKVnespslwmE3S4TDbpYIh90sEQ67WSIcdrNEOOxmifB5dmvI1KlTC+v77LNPbq23t7dw2e7u4lHD/H31PeMtu1kiHHazRDjsZolw2M0S4bCbJcJhN0uEw26WiP6Mzz4auA84jMr47LMj4nZJtwDfBDZns94UET+psS6Pzz7ADB06tLD+7LPPFtaLrg0/b968wmUvvfTSwrr1re7x2YEPgOkR8bykzwDLJC3IarMiYkazmjSz1qkZ9ojYAGzI7vdKWgWManVjZtZce3TMLqkLOA54Jpt0taQVkuZIOjBnmW5JSyUtbahTM2tIv8MuaX/gx8C1EbENuBMYB0ygsuWf2ddyETE7IiZGxMQm9GtmdepX2CUNpRL0H0bEQwARsTEidkbEh8DdwKTWtWlmjaoZdkkC7gFWRcT3q6aPrJrta8DK5rdnZs3Sn3fjTwYuBHokLc+m3QRMlTQBCGA1cHlLOrRS1To1e//99xfWly9fnltbsGBBbs2arz/vxj8F9HXervCcupl1Fn+CziwRDrtZIhx2s0Q47GaJcNjNEuGwmyWi5ldcm/pk/oqrWcvlfcXVW3azRDjsZolw2M0S4bCbJcJhN0uEw26WCIfdLBHtHrJ5C7Cm6vHB2bRO1Km9dWpf4N7q1czexuQV2vqhmk88ubS0U69N16m9dWpf4N7q1a7evBtvlgiH3SwRZYd9dsnPX6RTe+vUvsC91astvZV6zG5m7VP2lt3M2sRhN0tEKWGXdKakX0t6WdKNZfSQR9JqST2Slpc9Pl02ht4mSSurph0kaYGkl7KffY6xV1Jvt0h6PXvtlkuaXFJvoyU9KWmVpBckXZNNL/W1K+irLa9b24/ZJQ0BfgOcAawDngOmRsSv2tpIDkmrgYkRUfoHMCT9ObAduC8i/iib9j3grYj4bvaP8sCIuKFDersF2F72MN7ZaEUjq4cZB84BLqbE166grym04XUrY8s+CXg5Il6NiPeBB4CzS+ij40XEYuCt3SafDczN7s+l8sfSdjm9dYSI2BARz2f3e4Fdw4yX+toV9NUWZYR9FLC26vE6Omu89wCekLRMUnfZzfRhRERsgMofD3Boyf3sruYw3u202zDjHfPa1TP8eaPKCHtf18fqpPN/J0fE8cBZwFXZ7qr1T7+G8W6XPoYZ7wj1Dn/eqDLCvg4YXfX4cGB9CX30KSLWZz83AQ/TeUNRb9w1gm72c1PJ/Xykk4bx7muYcTrgtStz+PMywv4ccKSkL0jaG/g6ML+EPj5B0n7ZGydI2g/4Cp03FPV8YFp2fxrwaIm9fEynDOOdN8w4Jb92pQ9/HhFtvwGTqbwj/wrw7TJ6yOlrLPC/2e2FsnsD5lHZrfs9lT2iy4DPAouAl7KfB3VQbz8AeoAVVII1sqTevkzl0HAFsDy7TS77tSvoqy2vmz8ua5YIf4LOLBEOu1kiHHazRDjsZolw2M0S4bCbJcJhN0vE/wO+aLAjJW8ydgAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.imshow(X_train[0].reshape((28,28)),cmap='gray')\n",
    "plt.title('O numero é '+str(pred[0]))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
